### ISSUE TITLE
Filter include/exclude

### ISSUE THREAD

**Issue by Anian-igor** [umputun/feed-master#103]
Is this possible to get filter to include/exclude filter to RSS feed same like for YT feed?

**Comment by umputun** [comment]
Not sure what you mean exactly; however, the filters apply to feeds, not to the source (like YT).  Pls, explain your use case (better with some config example) and give me more details about what exactly you are trying to filter out and what you meant by "include"

**Comment by Anian-igor** [comment]
I have really huge feed from local radio broadcaster https://nv.ua/rss/podcasts/viyna-v-ukraini.xml
I want to filter just for few names in titles
I tried to filter by title but without luck
filter: 
      title: Сич
I have regexp but I don't know how to apply it. And didn't find example
/Фурса|Сич|Михайлов|Шабунін|Горєвой|Портников|Яковина|Тимошенко|Денисенко/i

**Comment by umputun** [comment]
Well, we do have an example, see https://github.com/umputun/feed-master/blob/master/_example/etc/fm.yml#L86

Generally, the filter is to exclude things, not to include them. I.e. filter doesn't act as "gimme those items only", but rather "gimme all the items except some". However, you can try some reversed/inverted regex, like `^(?:(?!first|second).)*$`. This particular one won't work because go's regex engine doesn't support  the  lookaround (e.g. the ?! negative lookahead operator).  I'm not sure if there is an alternative way to achive exclusion in regex, not a big expert in regex magic.

Alternatively, the small change in the code (adding configuration parameter "inversed" or smth like this) and using it to flip result of the check  in [this function](https://github.com/umputun/feed-master/blob/master/app/config/config.go#L68) can be much easier way to achive the desired result. Feel free to subimt a PR for this or ping the author of the original implementation of [regex filters](https://github.com/umputun/feed-master/pull/35)

**Comment by Anian-igor** [comment]
Yes. I see these examples. But I thought I miss include filter.
Thanks.

**Comment by umputun** [comment]
I have added the "invert" parameter to the filter. In your case, it will look like this:

```yml

    filter:
      title: (Фурса|Сич|Михайлов|Шабунін|Горєвой|Портников|Яковина|Тимошенко|Денисенко)
      invert: true
```

pls test it and let me know. You need to use :master docker image for those tests

**Comment by Anian-igor** [comment]
I updated master image. And Invert still don't work
`
feed-master  | 2022/12/23 14:30:19.849 [DEBUG] {proc/processor.go:52} refresh started
feed-master  | 2022/12/23 14:30:19.853 [DEBUG] {api/server.go:90} loading templates from webapp/templates/*
feed-master  | 2022/12/23 14:30:20.267 [INFO]  {proc/processor.go:92} filtered 17703 (Fri, 23 Dec 2022 19:38:53 +0000), radio-nv Війна в Україні: Чому Путін сере в секретну валізу — Сергій Фурса, Віталій Сич
feed-master  | 2022/12/23 14:30:20.275 [INFO]  {proc/store.go:54} save 1671824333-9da26a141ac244b5ddda211a7aa15a1ac3df94e8 - radio-nv - Війна в Україні: Чому Путін сере в секретну валізу — Сергій Фурса, Віталій Сич - 17703
feed-master  | 2022/12/23 14:30:20.306 [INFO]  {proc/store.go:54} save 1671794536-fa2b37434ccdbb6d86e21eb7db38a4f311ad2248 - radio-nv - Війна в Україні: Чи Баканов умисно не чіпав Московскьий патріархат? – Євстратій Зоря, ПЦУ - 17696
`

**Comment by umputun** [comment]
pls show the first line it prints to the log (with version info) and the filter part of your config

**Comment by Anian-igor** [comment]
```
  radio-nv:
    title: Радіо НВ - вибране
    description: НВ вибране
    link: https://podcasts.nv.ua
    language: "uk-ua"
    image: images/lavel_nv.png
    filter:
      title: (Фурса|Сич|Михайлов|Шабунін|Горєвой|Портников|Яковина|Тимошенко|Денисенко)
      invert: true
    sources:
      - name: Війна в Україні
        url: https://nv.ua/rss/podcasts/viyna-v-ukraini.xml
```

```
feed-master  | init container
feed-master  | set timezone America/Chicago (Fri Dec 23 14:41:38 CST 2022)
feed-master  | custom APP_UID not defined, using default uid=1001
feed-master  | chown: /srv/etc/fm.yml: Read-only file system
feed-master  | execute /srv/feed-master
feed-master  | feed-master master-04b9d0a-20221223T14:32:28
