### ISSUE TITLE
No feeds exist

### ISSUE THREAD

**Issue by aplsms** [umputun/feed-master#107]
After upgrade of feed-master got a strange issue:

youtube entry downloading to ./var/yt/filename.tmp.mp3, bot no media or rss folder have a mp3 files.

```
var
var/media
var/rss
var/yt
var/yt/c8c6441e71bd0cf87aea3ae9337095c159c273ef.tmp.mp3
var/yt/0b34296f366349996e2c745225216e4673292161.tmp.mp3
var/yt/d3423b4c1560c65966f62589956ebec40dbf710f.tmp.mp3
var/yt/a4a82e75a869d23869e165d7e673c3876e6b1556.tmp.mp3
var/yt/99e69be6b816a7300b4b2d1ea989316f05cc8f16.tmp.mp3
var/yt/eae5b46868e12e92df1b12b33c6224a13200409f.tmp.mp3
var/yt/fbf330c2c8d7c29c112bd45b90ed1a184bf75217.tmp.mp3
var/yt/2376a79134cd6b83571d2b56c727c50a4e8df999.tmp.mp3
var/yt/1b07375157f9a908576cd073cc83875916af723e.tmp.mp3
var/yt/3d2ab5df6b68b200e009d8261469e6a0b90a7957.tmp.mp3
var/yt/01ee9c28ca0fe761cfacfe83b58adcd8e83e92b5.tmp.mp3
var/yt/9d5ccd49b20b33d6602cae064ca933dcc4b357c9.tmp.mp3
var/yt/f4acdbe2c4b6971eaf89191bbf97eec0e1ec2411.tmp.mp3
var/yt/f1b7338a37c151ab86b748ffcf32d12d2e3ea858.tmp.mp3
var/feed-master.bdb
```

config:

```
feeds:
  ap-jucie:
    title: AP YouTube
    description: Andrii's best youtube-based podcas
    link: https://feeds.petrenko.me/feed/ap-jucie
    language: "ru-ru"
    image: images/jucie.jpg
    sources:
      - {name: "Самый Сік 2", url: https://feeds.petrenko.me/yt/rss/UCbH-3GF4hWQ8Ri1KjGR8kNQ}

youtube:
  base_url:  https://feeds.petrenko.me/yt/media
  dl_template: yt-dlp --extract-audio --audio-format=mp3 --audio-quality=0 -f m4a/bestaudio "https://www.youtube.com/watch?v={{.ID}}" --no-progress -o {{.FileName}}.tmp
  base_chan_url: "https://www.youtube.com/feeds/videos.xml?channel_id="
  base_playlist_url: "https://www.youtube.com/feeds/videos.xml?playlist_id="
  update: 300s
  max_per_channel: 2
  files_location: ./var/yt
  rss_location: ./var/rss
  channels:
  - {id: UCbH-3GF4hWQ8Ri1KjGR8kNQ, name: "Самий Сік 2", lang: "ru-ru"}

system:
  update: 5m
  max_per_feed: 50
  max_total: 100
  max_keep: 500
  base_url: https://feeds.petrenko.me
```
