### ISSUE TITLE
Outdated version yt-dlp

### ISSUE THREAD

**Issue by AndreiBurak** [umputun/feed-master#141]
Please update yt-dlp to the latest version to prevent errors when downloading new episodes.

**Comment by umputun** [comment]
Added options to the config file to update yt-dlp automatically; see #142.

```yml
  ytdlp_update: 
    interval: 24h # update interval for yt-dlp. If not set, yt-dlp will not be updated 
    cmd: "pip3 install --break-system-packages -U yt-dlp" # update yt-dlp command
```

This is a part of the `youtube` section. The command above is good if you use feed-master in the container. 
The change is on the master image only for now.

Please note: I have not tested it extensively, so feel free to give it a try and report the results. Updates would include corresponding log's messages._
