### ISSUE TITLE
Strange issues with yt part

### ISSUE THREAD

**Issue by umputun** [umputun/feed-master#57]
The youtube part is mostly fine, doing things as designed however there are 2 issues we need to address. I tend to believe both are somehow related to the way the youtube XML feed formed and I suspect some out-of-order entries from time to time, but not sure.

1. Sometimes we have an unhealthy loop with new entries detected, published, and removed right away. I don't really understand how this happens, but it seems to be related to updated entries. Currently, there is a hack in `youtube.Service` to prevent processing on the same entry for the second time. Obviously, this is just a hack, as this unbounded set will grow with time.
2. Somehow we get updates in the middle of the feed (the final RSS). This drives podcast clients insane and probably it has something to do with pub date out of order, not sure.

Both issues are reproducible with the current configuration, i.e. with this:
 
 ```
  echo-msk:
    title: Эхо Москвы
    description: Правильный, комбинированный фид избранных передач
    link: http://echo.msk.ru
    language: "ru-ru"
    image: images/echomsk.png
    telegram_channel: echomsk_u
    ext_date: yyyyddmm
    sources:
      - {name: "Живой Гвоздь", url: "https://worker.feed-master.com/yt/media/UCWAIvx2yYLK_xTYD4F2mUNw.xml"}
      - {name: "Александр Плющев", url: "https://worker.feed-master.com/yt/media/UCTVk323gzizpujtn2T_BL7w.xml"}
      - {name: "Дилетант", url: "https://worker.feed-master.com/yt/media/UCuIE7-5QzeAR6EdZXwDRwuQ.xml"}
      - {name: "Майкл Наки", url: "https://worker.feed-master.com/yt/media/UCgpSieplNxXxLXYAzJLLpng.xml"}
      - {name: "Татьяна Фельгенгауэр", url: "https://worker.feed-master.com/yt/media/UC0OiowQ-fTqw3Kq3bfopO_Q.xml"}
      - {name: "Юлия Латынина", url: "https://worker.feed-master.com/yt/media/UCzaqqlriSjVyc795m86GVyg.xml"}
      - {name: "Сергей Пархоменко", url: "https://worker.feed-master.com/yt/media/UC5wRw_R3kzwV5zGe7kzec8A.xml"}
      - {name: "Сергей Алексашенко", url: "https://worker.feed-master.com/yt/media/UCfePVJbfih7dkxrs8AInINg.xml"}
      - {name: "Евгения Альбац", url: "https://worker.feed-master.com/yt/media/UCZdyijiiXyMyrwTYMGOVxKA.xml"}
      - {name: "Виктор Шендерович", url: "https://worker.feed-master.com/yt/media/UCyYl1mXWoe4z_FcxzMaDHCw.xml"}
      - {name: "Александр Невзоров", url: "https://worker.feed-master.com/yt/media/UC8kI2B-UUv7A5u3AOUnHNMQ.xml"}
```
